"""empty message

Revision ID: 5767e638323c
Revises: f53a6076c5b9
Create Date: 2020-04-10 19:18:47.105449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5767e638323c'
down_revision = 'f53a6076c5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('intensity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity') as batch_op:
        batch_op.drop_column('intensity')
    # ### end Alembic commands ###
