"""empty message

Revision ID: 5efb8c1d8de1
Revises: dd29571452a9
Create Date: 2020-02-28 20:35:49.381930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efb8c1d8de1'
down_revision = 'dd29571452a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follows_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['follows_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'follows_id')
    # ### end Alembic commands ###
